#!/bin/bash
# limine-btrfs-snapshots.sh — regenerate /boot/limine/snapshots.cfg entries for
# the five most recent snapper snapshots, so they can be booted from Limine.
set -euo pipefail

ROOT_DEV=$(findmnt -n -o SOURCE /)
ROOT_UUID=$(blkid -s UUID -o value "$ROOT_DEV")
OUT="/boot/limine/snapshots.cfg"

{
  echo "# Snapshots BTRFS (autogenerated)"
} > "$OUT"

snapper -c root list 2>/dev/null | awk 'NR>2 {print $1}' | tail -n 5 | while read -r ID; do
  [[ -z $ID ]] && continue
  cat >> "$OUT" <<EOF

:Snapshot $ID
    PROTOCOL=linux
    KERNEL_PATH=boot:///vmlinuz-linux
    MODULE_PATH=boot:///initramfs-linux.img
    CMDLINE=root=UUID=$ROOT_UUID rootflags=subvol=.snapshots/$ID/snapshot rw
EOF
done

echo "Wrote $OUT"
