name: omarchy
description: Omarchy system theme
colors:
  background: "{{ background }}"
  ui_text: "{{ foreground }}"
  ui_primary: "{{ accent }}"
  ui_accent: "{{ accent }}"
  ui_border: "{{ muted }}"
  ui_label: "{{ accent }}"
  ui_ok: "{{ green }}"
  ui_warn: "{{ yellow }}"
  ui_error: "{{ red }}"
  ui_tool: "{{ cyan }}"
  ui_thinking: "{{ dark_foreground }}"
  banner_border: "{{ muted }}"
  banner_title: "{{ accent }}"
  banner_accent: "{{ accent }}"
  banner_dim: "{{ dark_foreground }}"
  banner_text: "{{ foreground }}"
  prompt: "{{ bright_foreground }}"
  input_rule: "{{ muted }}"
  response_border: "{{ accent }}"
  shell_dollar: "{{ blue }}"
  selection_bg: "{{ selection }}"
  session_label: "{{ accent }}"
  session_border: "{{ muted }}"
  status_bar_bg: "{{ dark_background }}"
  status_bar_text: "{{ foreground }}"
  status_bar_strong: "{{ accent }}"
  status_bar_dim: "{{ dark_foreground }}"
  status_bar_good: "{{ green }}"
  status_bar_warn: "{{ yellow }}"
  status_bar_bad: "{{ red }}"
  status_bar_critical: "{{ bright_red }}"
  voice_status_bg: "{{ dark_background }}"
  completion_menu_bg: "{{ lighter_background }}"
  completion_menu_current_bg: "{{ selection }}"
  completion_menu_meta_bg: "{{ lighter_background }}"
  completion_menu_meta_current_bg: "{{ selection }}"
  diff_added: "{{ mix background green 15% }}"
  diff_removed: "{{ mix background red 15% }}"
  diff_added_word: "{{ green }}"
  diff_removed_word: "{{ red }}"
  syntax_string: "{{ green }}"
  syntax_number: "{{ yellow }}"
  syntax_keyword: "{{ magenta }}"
  syntax_comment: "{{ muted }}"
